import type { Metadata } from "next";
import InfoPage from "../components/InfoPage";

export const metadata: Metadata = {
  title: "Chính sách biên tập | Dabangzz",
  description: "Cách Dabangzz chọn nguồn, biên tập tin tức, sử dụng AI và sửa sai.",
  alternates: { canonical: "/chinh-sach-bien-tap" },
};

export default function EditorialPolicyPage() {
  return <InfoPage eyebrow="MINH BẠCH NỘI DUNG" title="Chính sách biên tập" intro="Dabangzz giải thích tin mới Việt Nam và đăng trải nghiệm trực tiếp của Kim tại Việt Nam. Chúng tôi ưu tiên giá trị độc lập, nguồn rõ ràng và trải nghiệm đọc không gây hiểu nhầm." updatedAt="04.08.2026">
    <section><h2>1. Ba loại nội dung, ba cách kiểm chứng</h2><p><strong>Tin mới Việt Nam</strong> dựa trước hết vào cơ quan nhà nước, đơn vị chuyên môn hoặc tài liệu gốc. Bài phải cho biết nguồn, ngày cập nhật và phần nào là dữ kiện, phần nào là giải thích của Dabangzz.</p><p><strong>Chuyện cộng đồng</strong> chỉ dùng thảo luận công khai để phát hiện mô-típ. Chúng tôi không sao chép câu chữ, ảnh, ảnh chụp màn hình, tên tài khoản hay chi tiết có thể nhận dạng; nhiều tình huống được tổng hợp và viết mới cho độc giả Việt Nam.</p><p><strong>Kim ở Việt Nam</strong> chỉ đăng khi tác giả có trải nghiệm, ảnh hoặc hồ sơ mua hàng thực tế. Bài phải nêu thời điểm, địa điểm, phạm vi đã trực tiếp trải nghiệm, chi phí tự trả hay tài trợ, ưu điểm lẫn hạn chế. Nhận xét cá nhân được tách khỏi thông tin đối chiếu bên ngoài.</p></section>
    <section><h2>2. Không đăng lại và không “xào” bài</h2><p>Một liên kết nguồn không biến nội dung sao chép thành nội dung gốc. Mỗi bài phải bổ sung giá trị rõ ràng: giải thích bối cảnh, so sánh, chỉ ra giới hạn của dữ liệu hoặc đưa ra câu hỏi thực tế để người đọc tự kiểm tra.</p><p>Chúng tôi loại bỏ bài mỏng, tiêu đề không được nội dung hỗ trợ, tin đồn về người có thật, thông tin riêng tư, nội dung kích động và các chủ đề có nguy cơ gây hại.</p></section>
    <section><h2>3. Google Trends chỉ giúp tìm câu hỏi</h2><p>Dabangzz theo dõi Google Trends tại Việt Nam để hiểu độc giả đang cần biết điều gì. Lượng tìm kiếm không phải bằng chứng rằng một thông tin là đúng, quan trọng hay an toàn để đăng. Mọi dữ kiện xuất bản vẫn phải được kiểm tra bằng nguồn chính thức hoặc tài liệu gốc phù hợp.</p><p>Chúng tôi không chạy theo mọi từ khóa đang tăng. Các chủ đề chính trị vận động, cờ bạc, tin đồn cá nhân, thông tin y tế dễ gây hại và sự kiện chưa đủ căn cứ sẽ bị loại bỏ dù có lượng tìm kiếm cao.</p></section>
    <section><h2>4. Tin mới và thông tin nhạy cảm</h2><p>Với thời tiết, giao thông, quy định hoặc an toàn công cộng, bài viết luôn dẫn nguồn chính thức và nhắc người đọc kiểm tra bản cập nhật tại địa phương. Bài tin phải nêu số liệu, mốc thời gian, phạm vi áp dụng và giới hạn của dữ liệu khi nguồn có cung cấp. Dabangzz không thay thế cảnh báo khẩn cấp, tư vấn y tế, pháp lý hay tài chính.</p><p>Chúng tôi không dùng cộng đồng ẩn danh làm nguồn xác nhận cho một sự kiện. Nếu chưa thể xác minh điều cốt lõi, bài sẽ không được xuất bản.</p></section>
    <section><h2>5. AI và hình ảnh</h2><p>AI có thể hỗ trợ tạo bản nháp hoặc minh họa, nhưng con người chịu trách nhiệm về cấu trúc, nguồn và quyết định xuất bản. Ảnh AI được ghi rõ là minh họa, không được mô tả như ảnh hiện trường và không mô phỏng gương mặt của người có thật.</p><p>Trong bài trải nghiệm trực tiếp, ảnh của tác giả được ghi riêng, tối ưu cho web và loại bỏ dữ liệu thiết bị hoặc vị trí. Chúng tôi không dùng ảnh AI để giả làm bằng chứng về một chuyến đi, món ăn hay sản phẩm đã sử dụng.</p></section>
    <section><h2>6. Sửa sai, cập nhật và rút bài</h2><p>Sai sót quan trọng được sửa trực tiếp trong bài và ghi thời điểm cập nhật. Nếu thay đổi làm đảo ngược ý nghĩa chính, Dabangzz nêu rõ nội dung đã sửa thay vì âm thầm thay thế. Thông tin mới của cùng một sự việc được cập nhật vào bài hiện có khi phù hợp, không tạo nhiều URL gần như trùng nhau.</p><p>Nếu bài không còn đủ căn cứ, Dabangzz có thể tạm ngừng đề nghị lập chỉ mục trong khi kiểm tra. Khi hai bài trùng mục đích tìm kiếm, nội dung tốt hơn được giữ lại và URL còn lại chỉ được hợp nhất kèm chuyển hướng sau khi đánh giá thủ công. Phản hồi có thể gửi qua trang <a href="/lien-he">Liên hệ</a>.</p></section>
    <section><h2>7. Kiểm soát chất lượng và kho lưu trữ</h2><p>Dabangzz đã dừng tạo và phát hành tự động tin mới hoặc bài tái cấu trúc từ cộng đồng. Bài cũ có thể vẫn mở được để không làm mất đường dẫn, nhưng chỉ bài đáp ứng yêu cầu về nguồn, độ nguyên bản, độ mới và ích lợi thực tế mới xuất hiện trong trang chủ và sitemap.</p><p>Kho Chuyện Hàn Quốc đang được rà soát theo từng URL. Trạng thái không lập chỉ mục là biện pháp tạm thời, có thể đảo ngược; nó không phải là cách che giấu nội dung hay thay thế việc sửa bài.</p></section>
    <section><h2>8. Trách nhiệm và quan hệ thương mại</h2><p>Kim là người vận hành và chịu trách nhiệm xuất bản Dabangzz tại Bắc Ninh, Việt Nam. Thông tin về tác giả, phạm vi hoạt động và cách liên hệ được công khai tại trang <a href="/gioi-thieu">Giới thiệu</a>.</p><p>Dabangzz có mã xác minh AdSense nhưng hiện chưa được chấp thuận phân phối quảng cáo và chưa dùng liên kết tiếp thị liên kết. Khi quảng cáo, tài trợ hoặc hoa hồng được bổ sung, mối quan hệ đó phải được ghi rõ gần nội dung liên quan và không được quyết định kết luận biên tập.</p></section>
  </InfoPage>;
}
