import type { CommunityPost } from "./community-posts";

export const posts20260720: CommunityPost[] = [
  {
    slug: "my-pham-online-re-bat-thuong",
    category: "K-beauty · Tiêu dùng",
    title: "Mỹ phẩm online rẻ bất thường: kiểm tra gì trước khi bấm mua?",
    summary: "Giá thấp chưa chứng minh hàng giả, nhưng người mua cần nhiều dữ kiện hơn một ảnh đẹp và hàng nghìn lượt bán.",
    readTime: "6 phút đọc",
    hero: "TOO CHEAP\nTO TRUST?",
    images: [{ src: "/images/editorial/kiem-tra-my-pham-online-20260720.jpg", alt: "Minh họa bàn kiểm tra các hộp mỹ phẩm không nhãn bằng kính lúp và thẻ so sánh" }],
    publishedAt: "2026-07-20T20:30:00+07:00",
    sections: [
      { heading: "Đừng bắt đầu bằng việc đoán thật hay giả", paragraphs: ["Cùng một sản phẩm có thể chênh giá vì dung tích, thị trường phân phối, đợt thanh lý hoặc quà tặng kèm. Vì vậy, một mức giá thấp chỉ là tín hiệu cần kiểm tra thêm, không phải bằng chứng để kết luận về người bán.", "Hãy đối chiếu tên sản phẩm, dung tích, danh sách thành phần, hạn dùng và hình thức đóng gói với kênh chính thức dành cho đúng thị trường. Ảnh mờ, mô tả không thống nhất hoặc người bán né câu hỏi về nguồn hàng là lý do hợp lý để dừng lại." ]},
      { heading: "Thông tin người bán quan trọng hơn số sao", paragraphs: ["Kiểm tra lịch sử cửa hàng, chính sách đổi trả và việc nền tảng có xác minh gian hàng hay không. Đọc đánh giá mới nhất, ưu tiên nhận xét mô tả quá trình nhận hàng thay vì chỉ nhìn ảnh giống nhau hoặc câu khen rất ngắn.", "Lưu hóa đơn điện tử và quay lại tình trạng kiện hàng ngay khi mở nếu món đồ có giá trị. Mã lô hoặc mã vạch có thể hỗ trợ đối chiếu, nhưng không phải phép thử tại nhà đủ để bảo đảm tính xác thực." ], quote: "Không có một chi tiết đơn lẻ nào thay thế được việc kiểm tra cả chuỗi thông tin."},
      { heading: "Khi sản phẩm đến tay", paragraphs: ["Nếu niêm phong bất thường, mùi hoặc kết cấu khác rõ rệt so với thông tin công bố, đừng tiếp tục thử chỉ để tiếc tiền. Liên hệ người bán và bộ phận hỗ trợ của nền tảng bằng bằng chứng đã lưu.", "Bài viết hướng dẫn cách mua sắm thận trọng, không cáo buộc bất kỳ cửa hàng hay thương hiệu cụ thể nào và không thay thế kiểm định chuyên môn." ]},
    ],
  },
  {
    slug: "mot-nguoi-ngoi-ban-bon-cho-o-ca-phe",
    category: "Văn hóa · Cà phê",
    title: "Một người ngồi bàn bốn chỗ ở quán cà phê: có thật là thiếu ý thức?",
    summary: "Câu trả lời thay đổi theo giờ đông khách, cấu trúc quán và cách hai bên nói với nhau.",
    readTime: "5 phút đọc",
    hero: "ONE GUEST\nFOUR SEATS",
    images: [{ src: "/images/editorial/cho-ngoi-ca-phe-20260720.jpg", alt: "Minh họa một khách đi một mình chọn bàn nhỏ trong quán cà phê hiện đại" }],
    publishedAt: "2026-07-20T10:30:00+07:00",
    sections: [
      { heading: "Chiếc bàn không có một ý nghĩa cố định", paragraphs: ["Khi quán vắng, người đi một mình chọn bàn rộng để đặt túi hoặc máy tính không nhất thiết làm ai mất chỗ. Nhưng vào giờ cao điểm, bốn ghế bị giữ bởi một ly nước có thể khiến nhóm khác phải rời đi.", "Tranh luận thường căng vì khách nhìn vào số bàn đang trống, còn người vận hành nghĩ đến lượng khách có thể đến trong vài phút tới. Hai góc nhìn không hoàn toàn sai." ]},
      { heading: "Quan sát trước khi cắm sạc", paragraphs: ["Nếu quán có bàn đơn hoặc bàn chung, chọn chúng trước là cách đơn giản. Khi chỉ còn bàn lớn, bạn có thể hỏi nhân viên và chủ động chuyển nếu quán đông lên.", "Giữ chỗ bằng đồ đạc quá lâu trong khi rời quán dễ gây hiểu lầm. Ngược lại, nhân viên nên đề nghị đổi chỗ bằng lý do rõ ràng, không biến khách đi một mình thành đại diện cho mọi người từng ngồi lâu." ], quote: "Phép lịch sự tốt không cần ai phải xấu hổ vì đi cà phê một mình."},
      { heading: "Quy tắc rõ giúp cả hai bên nhẹ đầu", paragraphs: ["Một bảng hướng dẫn thời gian dùng bàn trong giờ cao điểm hoặc ký hiệu khu làm việc giúp khách quyết định trước khi gọi món. Quy tắc áp dụng nhất quán dễ được chấp nhận hơn lời nhắc tùy người.", "Bài viết kết hợp tín hiệu quan tâm về quán cà phê tại Việt Nam với các tranh luận công khai về chỗ ngồi; không sử dụng lời kể hay thông tin nhận dạng của cá nhân." ]},
    ],
  },
  {
    slug: "dat-do-an-ngay-mua-o-han-quoc",
    category: "Đời sống · Giao hàng",
    title: "Đặt đồ ăn ngày mưa ở Hàn: lịch sự không chỉ là nói cảm ơn",
    summary: "Địa chỉ rõ, điểm nhận an toàn và việc không thúc giục có ích hơn một lời áy náy dài.",
    readTime: "5 phút đọc",
    hero: "RAINY DAY\nDELIVERY",
    images: [{ src: "/images/editorial/giao-do-an-ngay-mua-20260720.jpg", alt: "Minh họa người giao đồ ăn trao túi hàng dưới mái che trong cơn mưa lớn" }],
    publishedAt: "2026-07-20T09:00:00+07:00",
    sections: [
      { heading: "Mưa làm mọi mốc thời gian kém chắc chắn", paragraphs: ["Đường trơn, tầm nhìn giảm và đơn hàng dồn cùng lúc khiến thời gian ước tính dễ thay đổi. Việc liên tục nhắn hỏi hoặc yêu cầu đi nhanh không giúp quãng đường an toàn hơn.", "Trước khi đặt, kiểm tra số tòa nhà, cổng vào và hướng dẫn lên tầng. Một ghi chú ngắn, chính xác có giá trị hơn nhiều câu xin lỗi nhưng thiếu thông tin." ]},
      { heading: "Chọn điểm nhận giảm thêm một chặng khó", paragraphs: ["Nếu lối vào phức tạp hoặc khu nhà hạn chế xe, hãy xuống sảnh hay mái che khi có thể. Bật điện thoại, theo dõi thông báo và trả lời nhanh để người giao không phải đứng lâu dưới mưa.", "Khi túi hàng bị ướt hoặc giao chậm, tách vấn đề vận chuyển khỏi thái độ của người giao. Chụp lại tình trạng và dùng kênh hỗ trợ của nền tảng nếu cần thay vì tranh cãi tại cửa." ], quote: "Tôn trọng người giao hàng bắt đầu bằng việc không biến sự vội của mình thành rủi ro của họ."},
      { heading: "Cảm ơn theo cách cụ thể", paragraphs: ["Một lời cảm ơn trực tiếp, đánh giá đúng trải nghiệm và hướng dẫn địa chỉ tốt cho lần sau đều thiết thực. Không cần biến việc đặt hàng thành cảm giác mắc nợ; đây là dịch vụ cần quy trình công bằng cho cả hai bên.", "Nội dung được viết từ các mô-típ đời sống giao hàng phổ biến, không lấy ảnh, tên người dùng hay chi tiết nhận dạng từ bài đăng cụ thể." ]},
    ],
  },
  {
    slug: "phoi-do-trong-one-room-mua-am",
    category: "Nhà ở · Đời sống",
    title: "Phơi đồ trong one-room mùa ẩm: càng treo sát càng lâu khô",
    summary: "Khoảng cách, luồng khí và thời điểm giặt quan trọng hơn việc chất thêm quần áo lên một chiếc giá nhỏ.",
    readTime: "6 phút đọc",
    hero: "INDOOR\nLAUNDRY",
    images: [{ src: "/images/editorial/phoi-do-mua-am-20260720.jpg", alt: "Minh họa người sắp xếp quần áo trên giá phơi trong căn phòng nhỏ ngày mưa" }],
    publishedAt: "2026-07-20T07:45:00+07:00",
    sections: [
      { heading: "Căn phòng nhỏ giữ lại hơi nước", paragraphs: ["Trong mùa mưa Hàn Quốc, cửa sổ đóng lâu và quần áo dày khiến độ ẩm tích tụ nhanh. Treo nhiều đồ sát nhau có vẻ tiết kiệm chỗ nhưng lại cản luồng khí, làm phần nách, túi và cạp quần khô chậm nhất.", "Một mẻ nhỏ vào thời điểm bạn có thể thông gió hoặc chạy chế độ hút ẩm thường hiệu quả hơn để cả tuần rồi giặt quá tải." ]},
      { heading: "Tạo đường đi cho không khí", paragraphs: ["Vắt đúng mức theo nhãn, giũ phẳng và xen kẽ đồ dài với đồ ngắn. Đặt quạt tuần hoàn ở khoảng cách an toàn hoặc dùng máy hút ẩm theo hướng dẫn, đồng thời đóng cửa phòng tắm để hơi ẩm không lan thêm.", "Không phơi ở hành lang thoát hiểm, trên thiết bị tỏa nhiệt hoặc nơi cản lối. Nếu dùng phòng giặt chung, lấy đồ đúng giờ để người sau không phải tự di chuyển đồ của bạn." ], quote: "Giá phơi không cần lớn hơn; khoảng trống giữa quần áo mới là phần đang làm việc."},
      { heading: "Mùi ẩm là tín hiệu cần đổi quy trình", paragraphs: ["Nếu đồ vẫn có mùi sau khi khô, hãy kiểm tra lồng giặt, lượng chất giặt và thời gian quần áo bị để ướt. Dùng nhiều hương thơm chỉ che tạm thời và có thể làm phòng kín nặng mùi hơn.", "Bài viết đưa ra mẹo sinh hoạt chung. Hãy tuân theo hướng dẫn của thiết bị, nhãn quần áo và quy định an toàn của nơi ở." ]},
    ],
  },
  {
    slug: "o-uot-trong-sanh-van-phong-han",
    category: "Văn hóa · Đời sống",
    title: "Ô ướt trong sảnh văn phòng Hàn: cất thế nào mới lịch sự?",
    summary: "Chiếc ô nhỏ có thể để lại cả vệt nước dài nếu người dùng chỉ nghĩ đến chỗ ngồi của mình.",
    readTime: "5 phút đọc",
    hero: "WET UMBRELLA\nETIQUETTE",
    images: [{ src: "/images/editorial/van-phong-ngay-mua-20260720.jpg", alt: "Minh họa nhân viên đặt ô ướt vào giá tại sảnh văn phòng Hàn Quốc" }],
    publishedAt: "2026-07-20T06:45:00+07:00",
    sections: [
      { heading: "Vệt nước là vấn đề chung", paragraphs: ["Vào ngày mưa, nhiều tòa nhà Hàn đặt giá ô, khay hứng nước hoặc túi bọc ở lối vào. Mục đích không phải làm chiếc ô trông gọn hơn mà giữ sàn không trơn và ngăn nước đi vào thang máy, hành lang.", "Trước khi bước vào, khép ô dưới mái che và giũ nhẹ ở nơi không bắn vào người khác. Nếu giá đã đầy, hỏi bảo vệ hoặc lễ tân thay vì đặt ngang lối đi." ]},
      { heading: "Đừng biến đồ dùng một lần thành mặc định", paragraphs: ["Một số nơi có túi bọc ô, nhưng người dùng có thể mang túi chống thấm tái sử dụng hoặc khăn nhỏ. Nếu dùng túi được cung cấp, hãy bỏ đúng nơi và không để lại trong tàu điện hay quán ăn sau đó.", "Ô giống nhau rất dễ bị cầm nhầm. Dấu nhận biết nhỏ trên tay cầm hữu ích hơn chiếm một khoảng lớn chỉ để tách ô của mình khỏi người khác." ], quote: "Phép lịch sự mùa mưa là kiểm soát phần nước đi theo mình vào không gian chung."},
      { heading: "Quan sát quy tắc của từng tòa nhà", paragraphs: ["Có văn phòng cho phép mang ô gấp đến bàn trong túi kín, nơi khác yêu cầu để toàn bộ ở sảnh. Làm theo biển hướng dẫn và thói quen chung sẽ an toàn hơn áp dụng một quy tắc cho mọi nơi.", "Bài viết tổng hợp mô-típ ứng xử mùa mưa và viết lại cho độc giả Việt Nam; không sử dụng hình ảnh hay câu chuyện nhận dạng của cá nhân." ]},
    ],
  },
];
