const articles = [
  { category: "Chuyện công sở", title: "Ngày đầu đi làm ở công ty Hàn: điều không ai nói trước", excerpt: "Từ cách chào hỏi đến bữa trưa tập thể, một câu chuyện được biên tập lại từ trải nghiệm thực tế.", tone: "coral" },
  { category: "Tình yêu", title: "Hẹn hò với người Hàn có thật sự giống phim?", excerpt: "Khác biệt trong cách nhắn tin, chia sẻ chi phí và giới thiệu với bạn bè.", tone: "violet" },
  { category: "Cuộc sống", title: "Ở nhà bán hầm tại Seoul: rẻ nhưng có đáng?", excerpt: "Tiền thuê, độ ẩm và những điều cần kiểm tra trước khi ký hợp đồng.", tone: "blue" },
  { category: "Văn hóa", title: "Vì sao người Hàn hỏi tuổi ngay lần đầu gặp?", excerpt: "Không chỉ là tò mò: tuổi tác ảnh hưởng đến cách xưng hô và quan hệ.", tone: "amber" },
  { category: "Du học", title: "Một tháng chi tiêu của du học sinh tại Busan", excerpt: "Tiền nhà, ăn uống, đi lại và việc làm thêm trong một bảng ngân sách.", tone: "green" },
  { category: "Mạng Hàn", title: "Chủ đề khiến cộng đồng Hàn tranh luận tuần này", excerpt: "Các luồng ý kiến nổi bật được tóm lược, ẩn danh và bổ sung bối cảnh.", tone: "navy" },
];

export default function Home() {
  const categories=["Mới nhất","Chuyện thật","Tình yêu","Công sở","Du học","Văn hóa","Đời sống Hàn"];
  return <main>
    <header className="site-header"><div className="topline"/><div className="header-inner"><a className="brand" href="#top">dabang<span>zz</span></a><nav><a href="#latest">Bài mới</a><a href="#topics">Chủ đề</a><a href="#about">Về chúng tôi</a></nav><button className="search" aria-label="Tìm kiếm">⌕</button></div></header>
    <section className="hero" id="top"><div className="hero-inner"><div className="hero-copy"><span className="kicker">CHUYỆN HÀN, KỂ THEO CÁCH DỄ HIỂU</span><h1>Chuyện thật từ Hàn,<br/><em>gần hơn với bạn</em></h1><p>Những câu chuyện, kinh nghiệm và chủ đề đang được quan tâm trong cộng đồng Hàn Quốc — được chọn lọc, kiểm chứng và kể lại bằng tiếng Việt.</p><a className="primary" href="#latest">Khám phá bài mới <span>→</span></a></div><div className="hero-art" aria-hidden="true"><div className="sun"/><div className="tower tower-a"/><div className="tower tower-b"/><div className="tower tower-c"/><span className="river">SEOUL · VIETNAM</span></div></div></section>
    <div className="category-bar" id="topics"><div>{categories.map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</div></div>
    <section className="content" id="latest"><div className="section-heading"><div><span>CÂU CHUYỆN MỚI</span><h2>Đang được đọc nhiều</h2></div><a href="#all">Xem tất cả →</a></div><div className="feature-grid"><article className="lead-card"><div className="lead-visual"><span>SEOUL<br/>STORY</span></div><div className="lead-body"><span className="label">Chuyện thật</span><h3>“Tôi đã sốc trong tuần đầu sống tại Hàn Quốc”</h3><p>Năm khác biệt văn hóa nhỏ nhưng khiến người nước ngoài nhớ mãi — được kể lại từ nhiều trải nghiệm cộng đồng.</p><div className="meta">19.07.2026 · 7 phút đọc</div></div></article><aside className="briefing"><span className="brief-label">HÔM NAY Ở HÀN</span><h3>Bản tin nhanh</h3><div className="stat"><strong>₩ 18.4</strong><span>VND / KRW<br/><b>Tham khảo</b></span></div><div className="weather"><strong>Seoul</strong><span>29° · Có mưa</span></div><div className="weather"><strong>Busan</strong><span>28° · Nhiều mây</span></div><p>Bối cảnh ngắn gọn giúp bạn hiểu câu chuyện trước khi đọc.</p></aside></div>
      <div className="article-grid" id="all">{articles.map(a=><article className="article-card" key={a.title}><div className={`thumb ${a.tone}`}><span>{a.category}</span></div><div className="article-body"><span className="label">{a.category}</span><h3>{a.title}</h3><p>{a.excerpt}</p><div className="meta">19.07.2026 · 5 phút đọc</div></div></article>)}</div></section>
    <section className="editorial"><strong>Nguyên tắc biên tập</strong><p>Nội dung được tổng hợp từ các chủ đề công khai, viết lại bằng góc nhìn riêng, ẩn danh nhân vật và bổ sung bối cảnh. Không sao chép nguyên văn hoặc đăng thông tin có thể nhận diện cá nhân.</p></section>
    <section className="newsletter"><div><span>MỖI TUẦN MỘT LẦN</span><h2>Hiểu Hàn Quốc<br/>qua những câu chuyện thật</h2><p>Nhận những bài đáng đọc nhất bằng tiếng Việt.</p></div><form><label className="sr-only" htmlFor="email">Email</label><input id="email" type="email" placeholder="Địa chỉ email"/><button type="submit">Đăng ký miễn phí</button></form></section>
    <footer id="about"><div className="footer-inner"><div><a className="brand light" href="#top">dabang<span>zz</span></a><p>Chuyện Hàn, kể cho người Việt.</p></div><div className="footer-links"><a href="#about">Giới thiệu</a><a href="#about">Nguyên tắc biên tập</a><a href="#about">Quyền riêng tư</a><a href="#about">Liên hệ</a></div></div><div className="copyright">© 2026 dabangzz. Nội dung mang tính tham khảo.</div></footer>
  </main>;
}
