const cards=[
 ["Chuyện công sở","Ngày đầu đi làm ở công ty Hàn: điều không ai nói trước","coral"],
 ["Tình yêu","Hẹn hò với người Hàn có thật sự giống phim?","violet"],
 ["Cuộc sống","Ở nhà bán hầm tại Seoul: rẻ nhưng có đáng?","blue"],
 ["Văn hóa","Vì sao người Hàn hỏi tuổi ngay lần đầu gặp?","amber"],
 ["Du học","Một tháng chi tiêu của du học sinh tại Busan","green"],
 ["Mạng Hàn","Chủ đề khiến cộng đồng Hàn tranh luận tuần này","navy"]
];
export default function Home(){return <main><header className="site-header"><div className="topline"/><div className="header-inner"><a className="brand" href="#top">dabang<span>zz</span></a><nav><a href="#latest">Bài mới</a><a href="#topics">Chủ đề</a><a href="#about">Về chúng tôi</a></nav><button className="search">⌕</button></div></header>
<section className="hero" id="top"><div className="hero-inner"><div className="hero-copy"><span className="kicker">CHUYỆN HÀN, KỂ THEO CÁCH DỄ HIỂU</span><h1>Chuyện thật từ Hàn,<br/><em>gần hơn với bạn</em></h1><p>Những câu chuyện đang được quan tâm trong cộng đồng Hàn Quốc — được chọn lọc, kiểm chứng và kể lại bằng tiếng Việt.</p><a className="primary" href="#latest">Khám phá bài mới <span>→</span></a></div><div className="hero-art"><div className="sun"/><div className="tower tower-a"/><div className="tower tower-b"/><div className="tower tower-c"/><span className="river">SEOUL · VIETNAM</span></div></div></section>
<div className="category-bar" id="topics"><div>{["Mới nhất","Chuyện thật","Tình yêu","Công sở","Du học","Văn hóa"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</div></div>
<section className="content" id="latest"><div className="section-heading"><div><span>CÂU CHUYỆN MỚI</span><h2>Đang được đọc nhiều</h2></div></div><div className="feature-grid"><a className="lead-card" href="/bai-viet/soc-van-hoa-han-quoc"><div className="lead-visual"><span>SEOUL<br/>STORY</span></div><div className="lead-body"><span className="label">Chuyện thật</span><h3>“Tôi đã sốc trong tuần đầu sống tại Hàn Quốc”</h3><p>Năm khác biệt văn hóa nhỏ nhưng khiến người nước ngoài nhớ mãi.</p><div className="meta">19.07.2026 · 7 phút đọc</div></div></a><aside className="briefing"><span className="brief-label">HÔM NAY Ở HÀN</span><h3>Bản tin nhanh</h3><div className="stat"><strong>₩ 18.4</strong><span>VND / KRW<br/><b>Tham khảo</b></span></div><div className="weather"><strong>Seoul</strong><span>29° · Có mưa</span></div><div className="weather"><strong>Busan</strong><span>28° · Nhiều mây</span></div></aside></div><div className="article-grid">{cards.map((a,i)=><a className="article-card" href={i===0?"/bai-viet/soc-van-hoa-han-quoc":"#"} key={a[1]}><div className={`thumb ${a[2]}`}><span>{a[0]}</span></div><div className="article-body"><span className="label">{a[0]}</span><h3>{a[1]}</h3><p>Trải nghiệm cộng đồng được ẩn danh, chọn lọc và biên tập lại cho độc giả Việt Nam.</p><div className="meta">5 phút đọc</div></div></a>)}</div></section>
<section className="editorial"><strong>Nguyên tắc biên tập</strong><p>Nội dung được tổng hợp từ chủ đề công khai, viết lại bằng góc nhìn riêng, ẩn danh nhân vật và bổ sung bối cảnh.</p></section><footer id="about"><div className="copyright">© 2026 dabangzz · Chuyện Hàn, kể cho người Việt.</div></footer></main>}
