import type { Metadata } from "next";
import InfoPage from "../components/InfoPage";

export const metadata: Metadata = {
  title: "Quyền riêng tư | Dabangzz",
  description: "Thông tin về dữ liệu, cookie và dịch vụ quảng cáo có thể được dùng trên Dabangzz.",
  alternates: { canonical: "/quyen-rieng-tu" },
};

export default function PrivacyPage() {
  return <InfoPage eyebrow="DỮ LIỆU & COOKIE" title="Chính sách quyền riêng tư" intro="Trang này giải thích dữ liệu có thể được xử lý khi bạn truy cập Dabangzz và những lựa chọn dành cho người đọc." updatedAt="04.08.2026">
    <section><h2>1. Dữ liệu kỹ thuật</h2><p>Máy chủ và nhà cung cấp hạ tầng có thể ghi nhận dữ liệu kỹ thuật cần thiết để vận hành và bảo vệ trang, như địa chỉ IP rút gọn hoặc đầy đủ tùy hệ thống, loại trình duyệt, thời gian truy cập, trang được yêu cầu và thông tin chẩn đoán lỗi.</p><p>Dabangzz không yêu cầu người đọc tạo tài khoản và không chủ động thu thập thông tin nhạy cảm qua nội dung bài viết.</p></section>
    <section><h2>2. Cookie và quảng cáo</h2><p>Dabangzz đã cài mã Google AdSense và tệp ads.txt để xác minh quyền quản lý trang, nhưng hiện chưa được chấp thuận phân phối quảng cáo. Khi mã của Google được tải, Google có thể nhận dữ liệu kỹ thuật như địa chỉ IP, loại trình duyệt, trang truy cập và thông tin thiết bị theo chính sách của Google, ngay cả khi chưa có quảng cáo hiển thị.</p><p>Nếu AdSense được chấp thuận và bắt đầu phân phối quảng cáo, Google và nhà cung cấp bên thứ ba có thể dùng cookie hoặc công nghệ tương tự để phân phối, đo lường và, khi được phép, cá nhân hóa quảng cáo. Dabangzz sẽ áp dụng cơ chế lựa chọn hoặc đồng ý cần thiết theo khu vực của người dùng. Người đọc có thể quản lý quảng cáo cá nhân hóa tại <a href="https://adssettings.google.com/" target="_blank" rel="noopener noreferrer">Cài đặt quảng cáo của Google</a> và xem cách Google dùng dữ liệu trên <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener noreferrer">các trang đối tác</a>.</p></section>
    <section><h2>3. Đo lường lượt truy cập</h2><p>Từ ngày 22/7/2026, Dabangzz sử dụng Google Analytics 4 để hiểu tổng thể cách người đọc tìm thấy và sử dụng trang. Công cụ này có thể ghi nhận lượt xem trang, thời gian tương tác, loại thiết bị, nguồn truy cập, khu vực gần đúng và các thao tác thông thường như cuộn trang hoặc nhấp vào liên kết ra ngoài.</p><p>Dabangzz không gửi tên, địa chỉ email hoặc nội dung liên hệ của người đọc vào Google Analytics. Dữ liệu đo lường được dùng để phát hiện lỗi, cải thiện điều hướng và lựa chọn chủ đề hữu ích hơn. Cách Google xử lý dữ liệu trên các trang đối tác được mô tả tại <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener noreferrer">chính sách dành cho trang đối tác của Google</a>.</p></section>
    <section><h2>4. Trình phát YouTube</h2><p>Các trang thuộc chuyên mục Âm nhạc · Lời Đáp dùng trình phát từ miền <strong>youtube-nocookie.com</strong>, là chế độ tăng cường quyền riêng tư của YouTube. Video không tự động phát. Khi trình phát được tải hoặc khi người đọc bấm phát, YouTube và Google vẫn có thể nhận dữ liệu kỹ thuật như địa chỉ IP, trình duyệt, thiết bị, trang giới thiệu và thao tác với trình phát theo chính sách của họ.</p><p>Dabangzz không gửi tên, email hoặc nội dung liên hệ vào trình phát. Khi người đọc chọn “Mở trên YouTube”, Dabangzz ghi một sự kiện tổng hợp không chứa dữ liệu nhận dạng để biết liên kết đã được dùng; cùng một video chỉ được ghi một lần trong mỗi phiên trình duyệt. Việc xem, bình luận, đăng ký hoặc tương tác trên YouTube chịu sự điều chỉnh của <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Chính sách quyền riêng tư của Google</a>.</p></section>
    <section><h2>5. Liên kết bên ngoài</h2><p>Bài tin tức có thể dẫn tới nguồn chính thức; trang âm nhạc có thể dẫn tới video và kênh YouTube chính thức. Trang bên ngoài có chính sách riêng; Dabangzz không kiểm soát cookie hoặc nội dung sau khi người đọc rời trang.</p></section>
    <section><h2>6. Thay đổi và câu hỏi</h2><p>Chính sách này được cập nhật ngày 4/8/2026 để làm rõ trạng thái AdSense và việc dùng trình phát YouTube ở chế độ tăng cường quyền riêng tư. Chính sách sẽ tiếp tục được sửa khi bổ sung biểu mẫu, quảng cáo hoặc công cụ khác làm thay đổi đáng kể cách xử lý dữ liệu. Câu hỏi và yêu cầu liên quan có thể gửi qua trang <a href="/lien-he">Liên hệ</a>.</p></section>
  </InfoPage>;
}
